name: CD

on:
  push:
    branches:
      - master

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  IMAGE_NAME: ghcr.io/prefeitura-rio/id-dados-rio


jobs:
  build-container:
    name: Build, publish and register
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and publish image
        run: |
          docker build -t $IMAGE_NAME:$GITHUB_SHA .
          docker build -t $IMAGE_NAME:latest .
          echo $GH_PAT | docker login ghcr.io -u gabriel-milan --password-stdin
          docker push $IMAGE_NAME:$GITHUB_SHA
          docker push $IMAGE_NAME:latest
